# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
      python -m ipykernel install --user &&
      pip3 install -r "/workspace/machine-learning-prework/requirements.txt"
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9005
    onOpen: ignore

# Install necessary packages
image:
  file: .gitpod.dockerfile
